### PR TITLE
Travis automatic testing

### PR DESCRIPTION
**Pull request by fidelram**
I added small test files and prepared some of the tests to run using travis.

### CODE REVIEW

**Comment by fidelram** [comment]
I recommend you set up a travis account to check that all tests are running properly. See https://docs.travis-ci.com/user/getting-started/

**Comment by tanghaibao** [comment]
@fidelram thanks for the travis setup!
@dvklopfenstein I'll merge this now and try to set up the Travis CI

**Comment by dvklopfenstein** [comment]
Hi Fidel,

Thanks for setting up Travis. I will take a look at it when I have a
moment. GOATOOLS was definitely in need of this.

I hope you don't mind, but I am going to make loading statsmodels optional
(take it out of setup.py) since loading (or you can if you want) it can be
painful in some setups - like Cygwin on a windows machine.

People can easily get started just using the local multiple test
corrections without the potential pain of loading statsmodels. This is the
same case as graphviz, which is an optional load for GOATOOLS. Loading
pygraphviz can be really painful and pydot is the alternate, which is much
easier to load.

Debra

**Comment by fidelram** [comment]
I noticed that some packages are required for some tools to run and I agree that they can be left out because they are an overhead for the installation. However, we have to think how to point the user to install those packages when a tool that requires it is used. Otherwise an exception is thrown. 

Regarding installation, I think that the best way is using anaconda which works on windows, mac and unix and contains all required packages precompiled. That's how the travis testing works, by installing difficult packages with anaconda.

**Comment by dvklopfenstein** [comment]
Sounds okay if works for the users.

I will have to checkout anaconda. It looks like cygwin users also use it.
On a personal note, it is too bad anaconda does not load pybluez
automatically. I would really to load pybluez, but not be required to have
Microsoft Visual Studio C++.

DV

**Pull request merged**
