### PR TITLE
Remove false requirement

### PR DESCRIPTION
**Pull request by flying-sheep**
This project doesn’t actually `import wget`

### CODE REVIEW

**Comment by dvklopfenstein** [comment]
Thank you for your interest in GOA TOOLs and for taking your time to create this pull request.

**Comment by flying-sheep** [comment]
Why did you close it?

**Comment by dvklopfenstein** [comment]
Why are you asking?

**Comment by dvklopfenstein** [comment]
Good pull request. Now it is merged. Closing now. Sorry about that.

**Pull request merged**
